Traceback (most recent call last):
  File "C:\Users\Antonio\Documents\GitHub\SDI_Tools\SpecTool.py", line 607, in writeSpecs
    specDoc = specDict[str(specData[2])]
              ~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'TTE24C'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\tkinter\__init__.py", line 1968, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Antonio\Documents\GitHub\SDI_Tools\SpecTool.py", line 627, in <lambda>
    treeview.tag_bind('tag?', "<Double-1>", lambda msgLabel: openFile(msgLabel))
                                                             ^^^^^^^^^^^^^^^^^^
TypeError: openFile() missing 1 required positional argument: 'msg'
