Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\tkinter\__init__.py", line 1968, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Antonio\Documents\GitHub\SDI_Tools\BulkLoads.py", line 370, in form
    formatFile(voltList)
  File "C:\Users\Antonio\Documents\GitHub\SDI_Tools\BulkLoads.py", line 164, in formatFile
    if type(rowData[hDict['volts']]) == list or type(rowData[hDict['ph']]) == list or ('amps' in hDict and type(rowData[hDict['amps']]) == list) or ('kw' in hDict and type(rowData[hDict['kw']]) == list):
                                                                                                                                                                                    ^^^^^^^^^^^^^
KeyError: 'amps'
KeyError: 'amps'